loading training instances, dir instances/randomip_n8_m6 idx 45
[0.01 0.02 0.03 0.04 0.09 0.1  0.12 0.15]
Set parameter Username
Academic license - for non-commercial use only - expires 2023-06-01
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/exmaple.py", line 119, in <module>
    prob = actor.compute_prob(curr_constraints, available_cuts)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/rl_cuts.py", line 120, in compute_prob
    prob = torch.nn.functional.softmax(self.model(constraints, cuts), dim=-1)
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/rl_cuts.py", line 96, in forward
    A_embed = self.lstm1.forward(constraints)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/rl_cuts.py", line 67, in forward
    inputs = torch.FloatTensor(input).view(1, -1, self.input_size)
RuntimeError: shape '[1, -1, 15]' is invalid for input of size 54
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/exmaple.py", line 119, in <module>
    prob = actor.compute_prob(curr_constraints, available_cuts)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/rl_cuts.py", line 120, in compute_prob
    prob = torch.nn.functional.softmax(self.model(constraints, cuts), dim=-1)
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/rl_cuts.py", line 96, in forward
    A_embed = self.lstm1.forward(constraints)
  File "/Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/rl_cuts.py", line 67, in forward
    inputs = torch.FloatTensor(input).view(1, -1, self.input_size)
RuntimeError: shape '[1, -1, 15]' is invalid for input of size 54
