2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_setup.py:_flush():76] Loading settings from /Users/zhangqiming/.config/wandb/settings
2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_setup.py:_flush():76] Loading settings from /Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/wandb/settings
2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'project/rl_cuts.py', 'program': 'rl_cuts.py'}
2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_init.py:_log_setup():428] Logging user logs to /Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/wandb/run-20220606_145712-12jalqcz/logs/debug.log
2022-06-06 14:57:12,613 INFO    MainThread:94005 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/zhangqiming/Desktop/RL_research/Reinforcement-Learning/project/wandb/run-20220606_145712-12jalqcz/logs/debug-internal.log
2022-06-06 14:57:12,614 INFO    MainThread:94005 [wandb_init.py:init():462] calling init triggers
2022-06-06 14:57:12,614 INFO    MainThread:94005 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2022-06-06 14:57:12,614 INFO    MainThread:94005 [wandb_init.py:init():515] starting backend
2022-06-06 14:57:12,614 INFO    MainThread:94005 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-06 14:57:12,629 INFO    MainThread:94005 [backend.py:ensure_launched():217] starting backend process...
2022-06-06 14:57:12,639 INFO    MainThread:94005 [backend.py:ensure_launched():222] started backend process with pid: 94050
2022-06-06 14:57:12,644 INFO    MainThread:94005 [wandb_init.py:init():525] backend started and connected
2022-06-06 14:57:12,655 INFO    MainThread:94005 [wandb_init.py:init():596] updated telemetry
2022-06-06 14:57:12,684 INFO    MainThread:94005 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-06 14:57:42,688 INFO    MainThread:94005 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-06 14:57:42,688 ERROR   MainThread:94005 [wandb_init.py:init():636] backend process timed out
2022-06-06 14:57:42,688 ERROR   MainThread:94005 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-06 14:57:42,698 ERROR   MainThread:94005 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 651, in init
    backend.cleanup()
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
